"""Restructing the Db schema

Revision ID: ab71572b112d
Revises: 18934af912ae
Create Date: 2024-11-10 20:15:57.432506

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ab71572b112d"
down_revision = "18934af912ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("frameworks_languages")
    op.drop_table("orms_languages")
    with op.batch_alter_table("frameworks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "languages", ["language_id"], ["id"])

    with op.batch_alter_table("languages", schema=None) as batch_op:
        batch_op.drop_column("assigned")

    with op.batch_alter_table("orms", schema=None) as batch_op:
        batch_op.add_column(sa.Column("language_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "languages", ["language_id"], ["id"])

    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("thumbnail", sa.String(length=255), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_column("thumbnail")

    with op.batch_alter_table("orms", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("language_id")

    with op.batch_alter_table("languages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "assigned",
                mysql.TINYINT(display_width=1),
                autoincrement=False,
                nullable=True,
            )
        )

    with op.batch_alter_table("frameworks", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("language_id")

    op.create_table(
        "orms_languages",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("language_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("orm_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"], ["languages.id"], name="orms_languages_ibfk_1"
        ),
        sa.ForeignKeyConstraint(["orm_id"], ["orms.id"], name="orms_languages_ibfk_2"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "frameworks_languages",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("language_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("framework_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["framework_id"], ["frameworks.id"], name="frameworks_languages_ibfk_1"
        ),
        sa.ForeignKeyConstraint(
            ["language_id"], ["languages.id"], name="frameworks_languages_ibfk_2"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
