"""Added ProjectVariantLanguageFramework and ProjectVariantLanguageOrm

Revision ID: 0107ac835c3f
Revises: 64cf51035bff
Create Date: 2024-11-28 17:16:15.943461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0107ac835c3f'
down_revision = '64cf51035bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_variant_framework',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_variant_language_id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_variant_language_id'], ['project_variant_language.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_variant_orm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_variant_language_id', sa.Integer(), nullable=False),
    sa.Column('orm_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orm_id'], ['orms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_variant_language_id'], ['project_variant_language.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_variant', schema=None) as batch_op:
        batch_op.alter_column('github',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_variant', schema=None) as batch_op:
        batch_op.alter_column('github',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    op.drop_table('project_variant_orm')
    op.drop_table('project_variant_framework')
    # ### end Alembic commands ###
