"""fix: TechnologySections was not inhereting from db.Model

Revision ID: 1e65697da5ac
Revises: cda66e5c5eeb
Create Date: 2024-11-12 18:22:00.862612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e65697da5ac'
down_revision = 'cda66e5c5eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('header', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technology_sections')
    # ### end Alembic commands ###
