"""Adding a seperate thumbnail table

Revision ID: 29fb0eb11541
Revises: ab71572b112d
Create Date: 2024-11-12 02:36:50.493081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29fb0eb11541'
down_revision = 'ab71572b112d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'thumbnails', ['thumbnail_id'], ['id'])
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('thumbnail_id')

    op.drop_table('thumbnails')
    # ### end Alembic commands ###
