"""ix: ondelete='CASCADE' for project_variant project_variant_language project_variant_technology

Revision ID: 64cf51035bff
Revises: 7f16fb247fa9
Create Date: 2024-11-14 12:51:11.974031

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "64cf51035bff"
down_revision = "7f16fb247fa9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_variant", schema=None) as batch_op:
        batch_op.add_column(sa.Column("project_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            None, "project", ["project_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("project_variant_language", schema=None) as batch_op:
        batch_op.drop_constraint("project_variant_language_ibfk_2", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "project_variant", ["project_variant_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("project_variant_technology", schema=None) as batch_op:
        batch_op.drop_constraint(
            "project_variant_technology_ibfk_1", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "project_variant", ["project_variant_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_variant_technology", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "project_variant_technology_ibfk_1",
            "project_variant",
            ["project_variant_id"],
            ["id"],
        )

    with op.batch_alter_table("project_variant_language", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "project_variant_language_ibfk_2",
            "project_variant",
            ["project_variant_id"],
            ["id"],
        )

    with op.batch_alter_table("project_variant", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("project_id")

    # ### end Alembic commands ###
