"""New project structure along with its variants

Revision ID: 7f16fb247fa9
Revises: 86c16d33af8a
Create Date: 2024-11-13 23:54:20.101533

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "7f16fb247fa9"
down_revision = "86c16d33af8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("problem_statement", sa.Text(), nullable=False),
        sa.Column("solution", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_variant",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("link", sa.String(length=255), nullable=True),
        sa.Column("github", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_variant_language",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("project_variant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["languages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_variant_id"],
            ["project_variant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_variant_technology",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("technology_id", sa.Integer(), nullable=False),
        sa.Column("project_variant_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_variant_id"],
            ["project_variant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technology_id"],
            ["technologies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("projects")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("description", mysql.TEXT(), nullable=False),
        sa.Column("link", mysql.VARCHAR(length=200), nullable=True),
        sa.Column("github_link", mysql.VARCHAR(length=200), nullable=True),
        sa.Column("technologies", mysql.VARCHAR(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("project_variant_technology")
    op.drop_table("project_variant_language")
    op.drop_table("project_variant")
    op.drop_table("project")
    # ### end Alembic commands ###
