"""fix: Added on cascade delete to orms and framworks

Revision ID: 86c16d33af8a
Revises: 02a4857ca72d
Create Date: 2024-11-12 18:50:51.201171

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "86c16d33af8a"
down_revision = "02a4857ca72d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("frameworks", schema=None) as batch_op:
        batch_op.drop_constraint("frameworks_ibfk_1", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "languages", ["language_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("orms", schema=None) as batch_op:
        batch_op.drop_constraint("orms_ibfk_1", type_="foreignkey")
        batch_op.create_foreign_key(
            None, "languages", ["language_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orms", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key("orms_ibfk_1", "languages", ["language_id"], ["id"])

    with op.batch_alter_table("frameworks", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "frameworks_ibfk_1", "languages", ["language_id"], ["id"]
        )

    # ### end Alembic commands ###
