"""Added libraries for variant languages

Revision ID: baeae21ffd03
Revises: 36123a921490
Create Date: 2024-12-10 16:32:47.283919

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "baeae21ffd03"
down_revision = "36123a921490"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_variant_lib",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_variant_language_id", sa.Integer(), nullable=False),
        sa.Column("lib_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["lib_id"], ["libraries.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["project_variant_language_id"],
            ["project_variant_language.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_variant_lib")
    # ### end Alembic commands ###
